# Generated by Django 4.2.5 on 2023-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppLacasona", "0002_remove_sendsong_message_sendsong_songname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendsong",
            name="deadline",
        ),
        migrations.AddField(
            model_name="sendsong",
            name="email",
            field=models.EmailField(default="correo@ejemplo.com", max_length=254),
        ),
        migrations.AddField(
            model_name="sendsong",
            name="url",
            field=models.URLField(default="https://ejemplo.com"),
        ),
    ]
